[variables]
PLAYWRIGHT_BROWSERS_PATH = '0'

[phases.install]
dependsOn = ['setup']
cmds = [
    'pnpm install --frozen-lockfile',
    'pnpm dlx playwright install --with-deps chromium'
]

[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build']

[start]
cmd = 'pnpm start'
